services:
  - name: nw-ml-backend
    type: web
    runtime: python
    repo: https://github.com/itsk2/MachineLearning.git  # Change this!
    branch: master  # Change if using a different branch
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5001 app:app
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://nowaste:uD2H_z_apa8DSsn@nowastecluster.egudtya.mongodb.net/nowaste?retryWrites=true&w=majority"
      - key: PORT
        value: "5001"
      - key: PYTHON_VERSION
        value: 3.10